"""Read-only explorer catalogue boundary."""
from typing import Protocol

from music_explorer.application.dto.explorer import ExplorerStoredTrack, ExplorerTrackSummary, MoodAxisEdge


class ExplorerRepository(Protocol):
    def metadata(self) -> dict[str, object]: ...
    def list_tracks(self, limit: int, after: str | None = None) -> tuple[dict[str, object], int, tuple[ExplorerStoredTrack, ...]]: ...
    def list_track_summaries(self, limit: int, cursor: str | None = None, query: str = '', order: str = 'title') -> tuple[dict[str, object], int, tuple[ExplorerTrackSummary, ...], str | None]: ...
    def candidate_snapshot(self) -> tuple[dict[str, object], tuple[ExplorerStoredTrack, ...]]: ...
    def current_graph_edges(self) -> tuple[dict[str, object] | None, tuple[MoodAxisEdge, ...]]: ...
    def track_ids(self) -> tuple[str, ...]: ...
    def read_track(self, track_id: str) -> ExplorerStoredTrack: ...
