"""Read-only explorer catalogue boundary."""
from typing import Protocol

from music_explorer.application.dto.explorer import ExplorerStoredTrack, ExplorerTrackSummary, MoodAxisEdge, MoodAxisGraph
from music_explorer.application.dto.playlists import PlayableTrackCandidate


class ExplorerRepository(Protocol):
    def metadata(self) -> dict[str, object]: ...
    def list_tracks(self, limit: int, after: str | None = None) -> tuple[dict[str, object], int, tuple[ExplorerStoredTrack, ...]]: ...
    def list_track_summaries(self, limit: int, cursor: str | None = None, query: str = '', order: str = 'title') -> tuple[dict[str, object], int, tuple[ExplorerTrackSummary, ...], str | None]:
        """Match every whitespace-separated token in visible title or artist.

        Matching is casefolded literal substring search; tokens may match either
        field independently, in any order. Blank queries do not filter results.
        """
        ...
    def candidate_snapshot(self) -> tuple[dict[str, object], tuple[ExplorerStoredTrack, ...]]: ...
    def current_graph_edges(self) -> tuple[dict[str, object] | None, tuple[MoodAxisEdge, ...]]: ...
    def current_positioned_graph_edges(self, sparse_k: int | None = None) -> tuple[dict[str, object] | None, tuple[MoodAxisEdge, ...]]: ...
    def mood_axis_graph_snapshot(self, mood: str | None = None, sparse_k: int = 10) -> MoodAxisGraph | None: ...
    def playlist_export_tracks(self) -> tuple[PlayableTrackCandidate, ...]: ...
    def track_ids(self) -> tuple[str, ...]: ...
    def read_track(self, track_id: str) -> ExplorerStoredTrack: ...
