from typing import Protocol
from music_analyzer.application.dto.catalogue import Inventory, ScanLimits, TrackMetadata


class FileInventory(Protocol):
    def inventory(self, root: str, limits: ScanLimits) -> Inventory: ...
    def matches(self, location: str, track_id: str) -> bool: ...


class Catalogue(Protocol):
    def register(self, inventory: Inventory) -> tuple[str, ...]: ...
    def locations(self, track_id: str) -> tuple[str, ...]: ...


class MetadataReader(Protocol):
    def read(self, location: str) -> TrackMetadata: ...
