from typing import Protocol, Iterable
from music_analyzer.application.dto.review import StoredTrack, ReviewReport


class ReviewRepository(Protocol):
    def track_ids(self) -> Iterable[str]: ...
    def read_track(self, track_id: str) -> StoredTrack: ...
    def set_override(self, track_id: str, field: str, value: str | None) -> None: ...


class ReviewOutput(Protocol):
    def write(self, reports: Iterable[ReviewReport], format: str, destination: str) -> None: ...
